/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#d3daef',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8fd',
        'surface-container-highest': '#dce2f7',
        'on-surface': '#141b2b',
        'on-surface-variant': '#424754',
        'inverse-surface': '#293040',
        'inverse-on-surface': '#edf0ff',
        outline: '#727785',
        'outline-variant': '#c2c6d6',
        'surface-tint': '#005ac2',
        primary: '#0058be',
        'on-primary': '#ffffff',
        'primary-container': '#2170e4',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        secondary: '#4648d4',
        'on-secondary': '#ffffff',
        'secondary-container': '#6063ee',
        'on-secondary-container': '#fffbff',
        tertiary: '#924700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b75b00',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed': '#311400',
        'on-tertiary-fixed-variant': '#723600',
        background: '#f9f9ff',
        'on-background': '#141b2b',
        'surface-variant': '#dce2f7',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-margin': '20px',
        gutter: '12px',
      },
      boxShadow: {
        level1: '0 2px 4px rgba(17, 24, 39, 0.05)',
        level2: '0 10px 15px rgba(17, 24, 39, 0.1)',
      }
    },
  },
  plugins: [],
}
